apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wnkn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wnkn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0033-app
  name: devfile-sample-wnkn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wnkn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wnkn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0033-tenant/tkrw-pr714-0075-0033-app/devfile-sample-wnkn@sha256:488ddaba37d0945bf572f00535125a6f86ca7203bc17de982eb9441b44f6f282
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
