apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wnkn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0033-tenant/tkrw-pr714-0075-0033-app/devfile-sample-wnkn@sha256:488ddaba37d0945bf572f00535125a6f86ca7203bc17de982eb9441b44f6f282
        name: my-nodejs
        resources: {}
status: {}
